services: 
  test-postgres:
    image: postgres:17.4-bookworm
    restart: always
    ports:
      - 5000:5432
    container_name: "test-postgres"
    environment:
      POSTGRES_USER: sony
      POSTGRES_PASSWORD: secret 
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - farm_test_postgres:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gocrazy -d chitchat"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
      image: adminer
      restart: always
      ports:
        - 9080:8080

volumes:
  farm_test_postgres:
