// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ranch/animal/v1/animal.proto

package pbgen

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OriginType int32

const (
	OriginType_ORIGIN_TYPE_UNSPECIFIED OriginType = 0
	OriginType_ORIGIN_TYPE_BORN        OriginType = 1
	OriginType_ORIGIN_TYPE_HATCHED     OriginType = 2
	OriginType_ORIGIN_TYPE_PURCHASED   OriginType = 3
)

// Enum value maps for OriginType.
var (
	OriginType_name = map[int32]string{
		0: "ORIGIN_TYPE_UNSPECIFIED",
		1: "ORIGIN_TYPE_BORN",
		2: "ORIGIN_TYPE_HATCHED",
		3: "ORIGIN_TYPE_PURCHASED",
	}
	OriginType_value = map[string]int32{
		"ORIGIN_TYPE_UNSPECIFIED": 0,
		"ORIGIN_TYPE_BORN":        1,
		"ORIGIN_TYPE_HATCHED":     2,
		"ORIGIN_TYPE_PURCHASED":   3,
	}
)

func (x OriginType) Enum() *OriginType {
	p := new(OriginType)
	*p = x
	return p
}

func (x OriginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OriginType) Descriptor() protoreflect.EnumDescriptor {
	return file_ranch_animal_v1_animal_proto_enumTypes[0].Descriptor()
}

func (OriginType) Type() protoreflect.EnumType {
	return &file_ranch_animal_v1_animal_proto_enumTypes[0]
}

func (x OriginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OriginType.Descriptor instead.
func (OriginType) EnumDescriptor() ([]byte, []int) {
	return file_ranch_animal_v1_animal_proto_rawDescGZIP(), []int{0}
}

type GENDER int32

const (
	GENDER_GENDER_UNSPECIFIED GENDER = 0
	GENDER_GENDER_MALE        GENDER = 1
	GENDER_GENDER_FEMALE      GENDER = 2
)

// Enum value maps for GENDER.
var (
	GENDER_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	GENDER_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x GENDER) Enum() *GENDER {
	p := new(GENDER)
	*p = x
	return p
}

func (x GENDER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GENDER) Descriptor() protoreflect.EnumDescriptor {
	return file_ranch_animal_v1_animal_proto_enumTypes[1].Descriptor()
}

func (GENDER) Type() protoreflect.EnumType {
	return &file_ranch_animal_v1_animal_proto_enumTypes[1]
}

func (x GENDER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GENDER.Descriptor instead.
func (GENDER) EnumDescriptor() ([]byte, []int) {
	return file_ranch_animal_v1_animal_proto_rawDescGZIP(), []int{1}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_SICK        HealthStatus = 2
	HealthStatus_HEALTH_STATUS_RECOVERED   HealthStatus = 3
	HealthStatus_HEALTH_STATUS_DEAD        HealthStatus = 4
	HealthStatus_HEALTH_STATUS_SOLD        HealthStatus = 5
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_SICK",
		3: "HEALTH_STATUS_RECOVERED",
		4: "HEALTH_STATUS_DEAD",
		5: "HEALTH_STATUS_SOLD",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_SICK":        2,
		"HEALTH_STATUS_RECOVERED":   3,
		"HEALTH_STATUS_DEAD":        4,
		"HEALTH_STATUS_SOLD":        5,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ranch_animal_v1_animal_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_ranch_animal_v1_animal_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_ranch_animal_v1_animal_proto_rawDescGZIP(), []int{2}
}

type Animal struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FarmId           string                 `protobuf:"bytes,2,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Species          string                 `protobuf:"bytes,4,opt,name=species,proto3" json:"species,omitempty"`
	Breed            string                 `protobuf:"bytes,5,opt,name=breed,proto3" json:"breed,omitempty"`
	BirthDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	OriginType       OriginType             `protobuf:"varint,7,opt,name=origin_type,json=originType,proto3,enum=ranch.animal.v1.OriginType" json:"origin_type,omitempty"`
	OriginFrom       string                 `protobuf:"bytes,8,opt,name=origin_from,json=originFrom,proto3" json:"origin_from,omitempty"`
	PurchasedPrice   float64                `protobuf:"fixed64,9,opt,name=purchased_price,json=purchasedPrice,proto3" json:"purchased_price,omitempty"`
	Gender           GENDER                 `protobuf:"varint,10,opt,name=gender,proto3,enum=ranch.animal.v1.GENDER" json:"gender,omitempty"`
	Weight           float64                `protobuf:"fixed64,11,opt,name=weight,proto3" json:"weight,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	IsActive         bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Notes            string                 `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Animal) Reset() {
	*x = Animal{}
	mi := &file_ranch_animal_v1_animal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Animal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Animal) ProtoMessage() {}

func (x *Animal) ProtoReflect() protoreflect.Message {
	mi := &file_ranch_animal_v1_animal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Animal.ProtoReflect.Descriptor instead.
func (*Animal) Descriptor() ([]byte, []int) {
	return file_ranch_animal_v1_animal_proto_rawDescGZIP(), []int{0}
}

func (x *Animal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Animal) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *Animal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Animal) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *Animal) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *Animal) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *Animal) GetOriginType() OriginType {
	if x != nil {
		return x.OriginType
	}
	return OriginType_ORIGIN_TYPE_UNSPECIFIED
}

func (x *Animal) GetOriginFrom() string {
	if x != nil {
		return x.OriginFrom
	}
	return ""
}

func (x *Animal) GetPurchasedPrice() float64 {
	if x != nil {
		return x.PurchasedPrice
	}
	return 0
}

func (x *Animal) GetGender() GENDER {
	if x != nil {
		return x.Gender
	}
	return GENDER_GENDER_UNSPECIFIED
}

func (x *Animal) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Animal) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

func (x *Animal) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Animal) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

var File_ranch_animal_v1_animal_proto protoreflect.FileDescriptor

const file_ranch_animal_v1_animal_proto_rawDesc = "" +
	"\n" +
	"\x1cranch/animal/v1/animal.proto\x12\x0franch.animal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x03\n" +
	"\x06Animal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afarm_id\x18\x02 \x01(\tR\x06farmId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x04 \x01(\tR\aspecies\x12\x14\n" +
	"\x05breed\x18\x05 \x01(\tR\x05breed\x129\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12<\n" +
	"\vorigin_type\x18\a \x01(\x0e2\x1b.ranch.animal.v1.OriginTypeR\n" +
	"originType\x12\x1f\n" +
	"\vorigin_from\x18\b \x01(\tR\n" +
	"originFrom\x12'\n" +
	"\x0fpurchased_price\x18\t \x01(\x01R\x0epurchasedPrice\x12/\n" +
	"\x06gender\x18\n" +
	" \x01(\x0e2\x17.ranch.animal.v1.GENDERR\x06gender\x12\x16\n" +
	"\x06weight\x18\v \x01(\x01R\x06weight\x12G\n" +
	"\x11registration_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x10registrationDate\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\x12\x14\n" +
	"\x05notes\x18\x0e \x01(\tR\x05notes*s\n" +
	"\n" +
	"OriginType\x12\x1b\n" +
	"\x17ORIGIN_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORIGIN_TYPE_BORN\x10\x01\x12\x17\n" +
	"\x13ORIGIN_TYPE_HATCHED\x10\x02\x12\x19\n" +
	"\x15ORIGIN_TYPE_PURCHASED\x10\x03*D\n" +
	"\x06GENDER\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02*\xad\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x16\n" +
	"\x12HEALTH_STATUS_SICK\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_RECOVERED\x10\x03\x12\x16\n" +
	"\x12HEALTH_STATUS_DEAD\x10\x04\x12\x16\n" +
	"\x12HEALTH_STATUS_SOLD\x10\x05b\x06proto3"

var (
	file_ranch_animal_v1_animal_proto_rawDescOnce sync.Once
	file_ranch_animal_v1_animal_proto_rawDescData []byte
)

func file_ranch_animal_v1_animal_proto_rawDescGZIP() []byte {
	file_ranch_animal_v1_animal_proto_rawDescOnce.Do(func() {
		file_ranch_animal_v1_animal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ranch_animal_v1_animal_proto_rawDesc), len(file_ranch_animal_v1_animal_proto_rawDesc)))
	})
	return file_ranch_animal_v1_animal_proto_rawDescData
}

var (
	file_ranch_animal_v1_animal_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
	file_ranch_animal_v1_animal_proto_msgTypes  = make([]protoimpl.MessageInfo, 1)
	file_ranch_animal_v1_animal_proto_goTypes   = []any{
		(OriginType)(0),               // 0: ranch.animal.v1.OriginType
		(GENDER)(0),                   // 1: ranch.animal.v1.GENDER
		(HealthStatus)(0),             // 2: ranch.animal.v1.HealthStatus
		(*Animal)(nil),                // 3: ranch.animal.v1.Animal
		(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	}
)
var file_ranch_animal_v1_animal_proto_depIdxs = []int32{
	4, // 0: ranch.animal.v1.Animal.birth_date:type_name -> google.protobuf.Timestamp
	0, // 1: ranch.animal.v1.Animal.origin_type:type_name -> ranch.animal.v1.OriginType
	1, // 2: ranch.animal.v1.Animal.gender:type_name -> ranch.animal.v1.GENDER
	4, // 3: ranch.animal.v1.Animal.registration_date:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ranch_animal_v1_animal_proto_init() }
func file_ranch_animal_v1_animal_proto_init() {
	if File_ranch_animal_v1_animal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ranch_animal_v1_animal_proto_rawDesc), len(file_ranch_animal_v1_animal_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ranch_animal_v1_animal_proto_goTypes,
		DependencyIndexes: file_ranch_animal_v1_animal_proto_depIdxs,
		EnumInfos:         file_ranch_animal_v1_animal_proto_enumTypes,
		MessageInfos:      file_ranch_animal_v1_animal_proto_msgTypes,
	}.Build()
	File_ranch_animal_v1_animal_proto = out.File
	file_ranch_animal_v1_animal_proto_goTypes = nil
	file_ranch_animal_v1_animal_proto_depIdxs = nil
}
