receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:

exporters: 
  zipkin:
    endpoint: "http://jaeger:9411/api/v2/spans"

  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: metric

  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:  
      insecure: true
    

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [zipkin]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]
