global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'docker-compose'
    replica: 'prometheus-1'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:9464']
    scrape_interval: 30s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 30s

  - job_name: 'jaeger-all-in-one'
    static_configs:
      - targets: ['jaeger-all-in-one:14269']
    scrape_interval: 30s

  - job_name: 'jaeger-query'
    static_configs:
      - targets: ['jaeger-query:16687']
    scrape_interval: 30s

# Remote write configuration for Tempo metrics generator
remote_write:
  - url: http://tempo:3200/api/v1/push
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
