// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pbgen "github.com/sony-nurdianto/farm/auth/internal/pbgen"
)

// MockServiceUsecase is a mock of ServiceUsecase interface.
type MockServiceUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockServiceUsecaseMockRecorder
}

// MockServiceUsecaseMockRecorder is the mock recorder for MockServiceUsecase.
type MockServiceUsecaseMockRecorder struct {
	mock *MockServiceUsecase
}

// NewMockServiceUsecase creates a new mock instance.
func NewMockServiceUsecase(ctrl *gomock.Controller) *MockServiceUsecase {
	mock := &MockServiceUsecase{ctrl: ctrl}
	mock.recorder = &MockServiceUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceUsecase) EXPECT() *MockServiceUsecaseMockRecorder {
	return m.recorder
}

// UserRegister mocks base method.
func (m *MockServiceUsecase) UserRegister(user *pbgen.RegisterUserRequest) (*pbgen.RegisterUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRegister", user)
	ret0, _ := ret[0].(*pbgen.RegisterUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserRegister indicates an expected call of UserRegister.
func (mr *MockServiceUsecaseMockRecorder) UserRegister(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRegister", reflect.TypeOf((*MockServiceUsecase)(nil).UserRegister), user)
}
