// Code generated by MockGen. DO NOT EDIT.
// Source: tokhan.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	paseto "github.com/o1egl/paseto"
)

// MockTokhan is a mock of Tokhan interface.
type MockTokhan struct {
	ctrl     *gomock.Controller
	recorder *MockTokhanMockRecorder
}

// MockTokhanMockRecorder is the mock recorder for MockTokhan.
type MockTokhanMockRecorder struct {
	mock *MockTokhan
}

// NewMockTokhan creates a new mock instance.
func NewMockTokhan(ctrl *gomock.Controller) *MockTokhan {
	mock := &MockTokhan{ctrl: ctrl}
	mock.recorder = &MockTokhanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokhan) EXPECT() *MockTokhanMockRecorder {
	return m.recorder
}

// CreateWebToken mocks base method.
func (m *MockTokhan) CreateWebToken(subject string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebToken", subject)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebToken indicates an expected call of CreateWebToken.
func (mr *MockTokhanMockRecorder) CreateWebToken(subject interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebToken", reflect.TypeOf((*MockTokhan)(nil).CreateWebToken), subject)
}

// VerifyWebToken mocks base method.
func (m *MockTokhan) VerifyWebToken(token string) (paseto.JSONToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebToken", token)
	ret0, _ := ret[0].(paseto.JSONToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyWebToken indicates an expected call of VerifyWebToken.
func (mr *MockTokhanMockRecorder) VerifyWebToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebToken", reflect.TypeOf((*MockTokhan)(nil).VerifyWebToken), token)
}
