// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sony-nurdianto/farm/shared_lib/Go/kafkaev/kev (interfaces: Kafka,KevProducer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kafka "github.com/confluentinc/confluent-kafka-go/v2/kafka"
	gomock "github.com/golang/mock/gomock"
	kev "github.com/sony-nurdianto/farm/shared_lib/Go/kafkaev/kev"
)

// MockKafka is a mock of Kafka interface.
type MockKafka struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaMockRecorder
}

// MockKafkaMockRecorder is the mock recorder for MockKafka.
type MockKafkaMockRecorder struct {
	mock *MockKafka
}

// NewMockKafka creates a new mock instance.
func NewMockKafka(ctrl *gomock.Controller) *MockKafka {
	mock := &MockKafka{ctrl: ctrl}
	mock.recorder = &MockKafkaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafka) EXPECT() *MockKafkaMockRecorder {
	return m.recorder
}

// NewProducer mocks base method.
func (m *MockKafka) NewProducer(arg0 *kafka.ConfigMap) (kev.KevProducer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewProducer", arg0)
	ret0, _ := ret[0].(kev.KevProducer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewProducer indicates an expected call of NewProducer.
func (mr *MockKafkaMockRecorder) NewProducer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewProducer", reflect.TypeOf((*MockKafka)(nil).NewProducer), arg0)
}

// MockKevProducer is a mock of KevProducer interface.
type MockKevProducer struct {
	ctrl     *gomock.Controller
	recorder *MockKevProducerMockRecorder
}

// MockKevProducerMockRecorder is the mock recorder for MockKevProducer.
type MockKevProducerMockRecorder struct {
	mock *MockKevProducer
}

// NewMockKevProducer creates a new mock instance.
func NewMockKevProducer(ctrl *gomock.Controller) *MockKevProducer {
	mock := &MockKevProducer{ctrl: ctrl}
	mock.recorder = &MockKevProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKevProducer) EXPECT() *MockKevProducerMockRecorder {
	return m.recorder
}

// AbortTransaction mocks base method.
func (m *MockKevProducer) AbortTransaction(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortTransaction", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortTransaction indicates an expected call of AbortTransaction.
func (mr *MockKevProducerMockRecorder) AbortTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortTransaction", reflect.TypeOf((*MockKevProducer)(nil).AbortTransaction), arg0)
}

// BeginTransaction mocks base method.
func (m *MockKevProducer) BeginTransaction() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction")
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockKevProducerMockRecorder) BeginTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockKevProducer)(nil).BeginTransaction))
}

// Close mocks base method.
func (m *MockKevProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockKevProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKevProducer)(nil).Close))
}

// CommitTransaction mocks base method.
func (m *MockKevProducer) CommitTransaction(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockKevProducerMockRecorder) CommitTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockKevProducer)(nil).CommitTransaction), arg0)
}

// Events mocks base method.
func (m *MockKevProducer) Events() chan kafka.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events")
	ret0, _ := ret[0].(chan kafka.Event)
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockKevProducerMockRecorder) Events() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockKevProducer)(nil).Events))
}

// Flush mocks base method.
func (m *MockKevProducer) Flush(arg0 int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockKevProducerMockRecorder) Flush(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockKevProducer)(nil).Flush), arg0)
}

// InitTransactions mocks base method.
func (m *MockKevProducer) InitTransactions(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitTransactions", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitTransactions indicates an expected call of InitTransactions.
func (mr *MockKevProducerMockRecorder) InitTransactions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitTransactions", reflect.TypeOf((*MockKevProducer)(nil).InitTransactions), arg0)
}

// KafkaProducer mocks base method.
func (m *MockKevProducer) KafkaProducer() *kafka.Producer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KafkaProducer")
	ret0, _ := ret[0].(*kafka.Producer)
	return ret0
}

// KafkaProducer indicates an expected call of KafkaProducer.
func (mr *MockKevProducerMockRecorder) KafkaProducer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KafkaProducer", reflect.TypeOf((*MockKevProducer)(nil).KafkaProducer))
}

// Produce mocks base method.
func (m *MockKevProducer) Produce(arg0 *kafka.Message, arg1 chan kafka.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockKevProducerMockRecorder) Produce(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockKevProducer)(nil).Produce), arg0, arg1)
}
