// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: farm/v1/farm.proto

package pbgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FarmAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	Village       string                 `protobuf:"bytes,3,opt,name=village,proto3" json:"village,omitempty"`
	SubDistrict   string                 `protobuf:"bytes,4,opt,name=sub_district,json=subDistrict,proto3" json:"sub_district,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Province      string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	PostalCode    string                 `protobuf:"bytes,7,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmAddress) Reset() {
	*x = FarmAddress{}
	mi := &file_farm_v1_farm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmAddress) ProtoMessage() {}

func (x *FarmAddress) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmAddress.ProtoReflect.Descriptor instead.
func (*FarmAddress) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{0}
}

func (x *FarmAddress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FarmAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *FarmAddress) GetVillage() string {
	if x != nil {
		return x.Village
	}
	return ""
}

func (x *FarmAddress) GetSubDistrict() string {
	if x != nil {
		return x.SubDistrict
	}
	return ""
}

func (x *FarmAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *FarmAddress) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *FarmAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *FarmAddress) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FarmAddress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Farm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FarmerId      string                 `protobuf:"bytes,2,opt,name=farmer_id,json=farmerId,proto3" json:"farmer_id,omitempty"`
	FarmName      string                 `protobuf:"bytes,3,opt,name=farm_name,json=farmName,proto3" json:"farm_name,omitempty"`
	FarmType      string                 `protobuf:"bytes,4,opt,name=farm_type,json=farmType,proto3" json:"farm_type,omitempty"`
	FarmSize      float64                `protobuf:"fixed64,5,opt,name=farm_size,json=farmSize,proto3" json:"farm_size,omitempty"`
	FarmStatus    string                 `protobuf:"bytes,6,opt,name=farm_status,json=farmStatus,proto3" json:"farm_status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Address       *FarmAddress           `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Farm) Reset() {
	*x = Farm{}
	mi := &file_farm_v1_farm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Farm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Farm) ProtoMessage() {}

func (x *Farm) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Farm.ProtoReflect.Descriptor instead.
func (*Farm) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{1}
}

func (x *Farm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Farm) GetFarmerId() string {
	if x != nil {
		return x.FarmerId
	}
	return ""
}

func (x *Farm) GetFarmName() string {
	if x != nil {
		return x.FarmName
	}
	return ""
}

func (x *Farm) GetFarmType() string {
	if x != nil {
		return x.FarmType
	}
	return ""
}

func (x *Farm) GetFarmSize() float64 {
	if x != nil {
		return x.FarmSize
	}
	return 0
}

func (x *Farm) GetFarmStatus() string {
	if x != nil {
		return x.FarmStatus
	}
	return ""
}

func (x *Farm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Farm) GetAddress() *FarmAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Farm) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Farm) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateFarmAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	Village       string                 `protobuf:"bytes,2,opt,name=village,proto3" json:"village,omitempty"`
	SubDistrict   string                 `protobuf:"bytes,3,opt,name=sub_district,json=subDistrict,proto3" json:"sub_district,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Province      string                 `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFarmAddress) Reset() {
	*x = CreateFarmAddress{}
	mi := &file_farm_v1_farm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFarmAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFarmAddress) ProtoMessage() {}

func (x *CreateFarmAddress) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFarmAddress.ProtoReflect.Descriptor instead.
func (*CreateFarmAddress) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFarmAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateFarmAddress) GetVillage() string {
	if x != nil {
		return x.Village
	}
	return ""
}

func (x *CreateFarmAddress) GetSubDistrict() string {
	if x != nil {
		return x.SubDistrict
	}
	return ""
}

func (x *CreateFarmAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateFarmAddress) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CreateFarmAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type CreateFarm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmerId      string                 `protobuf:"bytes,1,opt,name=farmer_id,json=farmerId,proto3" json:"farmer_id,omitempty"`
	FarmName      string                 `protobuf:"bytes,2,opt,name=farm_name,json=farmName,proto3" json:"farm_name,omitempty"`
	FarmType      string                 `protobuf:"bytes,3,opt,name=farm_type,json=farmType,proto3" json:"farm_type,omitempty"`
	FarmSize      float64                `protobuf:"fixed64,4,opt,name=farm_size,json=farmSize,proto3" json:"farm_size,omitempty"`
	FarmStatus    string                 `protobuf:"bytes,5,opt,name=farm_status,json=farmStatus,proto3" json:"farm_status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFarm) Reset() {
	*x = CreateFarm{}
	mi := &file_farm_v1_farm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFarm) ProtoMessage() {}

func (x *CreateFarm) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFarm.ProtoReflect.Descriptor instead.
func (*CreateFarm) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFarm) GetFarmerId() string {
	if x != nil {
		return x.FarmerId
	}
	return ""
}

func (x *CreateFarm) GetFarmName() string {
	if x != nil {
		return x.FarmName
	}
	return ""
}

func (x *CreateFarm) GetFarmType() string {
	if x != nil {
		return x.FarmType
	}
	return ""
}

func (x *CreateFarm) GetFarmSize() float64 {
	if x != nil {
		return x.FarmSize
	}
	return 0
}

func (x *CreateFarm) GetFarmStatus() string {
	if x != nil {
		return x.FarmStatus
	}
	return ""
}

func (x *CreateFarm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateFarmData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FarmName      string                 `protobuf:"bytes,3,opt,name=farm_name,json=farmName,proto3" json:"farm_name,omitempty"`
	FarmType      string                 `protobuf:"bytes,4,opt,name=farm_type,json=farmType,proto3" json:"farm_type,omitempty"`
	FarmSize      float64                `protobuf:"fixed64,5,opt,name=farm_size,json=farmSize,proto3" json:"farm_size,omitempty"`
	FarmStatus    string                 `protobuf:"bytes,6,opt,name=farm_status,json=farmStatus,proto3" json:"farm_status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFarmData) Reset() {
	*x = UpdateFarmData{}
	mi := &file_farm_v1_farm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFarmData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFarmData) ProtoMessage() {}

func (x *UpdateFarmData) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFarmData.ProtoReflect.Descriptor instead.
func (*UpdateFarmData) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFarmData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFarmData) GetFarmName() string {
	if x != nil {
		return x.FarmName
	}
	return ""
}

func (x *UpdateFarmData) GetFarmType() string {
	if x != nil {
		return x.FarmType
	}
	return ""
}

func (x *UpdateFarmData) GetFarmSize() float64 {
	if x != nil {
		return x.FarmSize
	}
	return 0
}

func (x *UpdateFarmData) GetFarmStatus() string {
	if x != nil {
		return x.FarmStatus
	}
	return ""
}

func (x *UpdateFarmData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateFarmAddressData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	Village       string                 `protobuf:"bytes,3,opt,name=village,proto3" json:"village,omitempty"`
	SubDistrict   string                 `protobuf:"bytes,4,opt,name=sub_district,json=subDistrict,proto3" json:"sub_district,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Province      string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	PostalCode    string                 `protobuf:"bytes,7,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFarmAddressData) Reset() {
	*x = UpdateFarmAddressData{}
	mi := &file_farm_v1_farm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFarmAddressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFarmAddressData) ProtoMessage() {}

func (x *UpdateFarmAddressData) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFarmAddressData.ProtoReflect.Descriptor instead.
func (*UpdateFarmAddressData) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFarmAddressData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFarmAddressData) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UpdateFarmAddressData) GetVillage() string {
	if x != nil {
		return x.Village
	}
	return ""
}

func (x *UpdateFarmAddressData) GetSubDistrict() string {
	if x != nil {
		return x.SubDistrict
	}
	return ""
}

func (x *UpdateFarmAddressData) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateFarmAddressData) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UpdateFarmAddressData) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type CreateFarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Farm          *CreateFarm            `protobuf:"bytes,1,opt,name=farm,proto3" json:"farm,omitempty"`
	Address       *CreateFarmAddress     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFarmRequest) Reset() {
	*x = CreateFarmRequest{}
	mi := &file_farm_v1_farm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFarmRequest) ProtoMessage() {}

func (x *CreateFarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFarmRequest.ProtoReflect.Descriptor instead.
func (*CreateFarmRequest) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{6}
}

func (x *CreateFarmRequest) GetFarm() *CreateFarm {
	if x != nil {
		return x.Farm
	}
	return nil
}

func (x *CreateFarmRequest) GetAddress() *CreateFarmAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type CreateFarmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmId        string                 `protobuf:"bytes,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	FarmName      string                 `protobuf:"bytes,2,opt,name=farm_name,json=farmName,proto3" json:"farm_name,omitempty"`
	AddressId     string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFarmResponse) Reset() {
	*x = CreateFarmResponse{}
	mi := &file_farm_v1_farm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFarmResponse) ProtoMessage() {}

func (x *CreateFarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFarmResponse.ProtoReflect.Descriptor instead.
func (*CreateFarmResponse) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{7}
}

func (x *CreateFarmResponse) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *CreateFarmResponse) GetFarmName() string {
	if x != nil {
		return x.FarmName
	}
	return ""
}

func (x *CreateFarmResponse) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *CreateFarmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateFarmResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetFarmByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFarmByIDRequest) Reset() {
	*x = GetFarmByIDRequest{}
	mi := &file_farm_v1_farm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFarmByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFarmByIDRequest) ProtoMessage() {}

func (x *GetFarmByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFarmByIDRequest.ProtoReflect.Descriptor instead.
func (*GetFarmByIDRequest) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{8}
}

func (x *GetFarmByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFarmByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Farm          *Farm                  `protobuf:"bytes,1,opt,name=farm,proto3" json:"farm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFarmByIDResponse) Reset() {
	*x = GetFarmByIDResponse{}
	mi := &file_farm_v1_farm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFarmByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFarmByIDResponse) ProtoMessage() {}

func (x *GetFarmByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFarmByIDResponse.ProtoReflect.Descriptor instead.
func (*GetFarmByIDResponse) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{9}
}

func (x *GetFarmByIDResponse) GetFarm() *Farm {
	if x != nil {
		return x.Farm
	}
	return nil
}

type GetFarmListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFarmListRequest) Reset() {
	*x = GetFarmListRequest{}
	mi := &file_farm_v1_farm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFarmListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFarmListRequest) ProtoMessage() {}

func (x *GetFarmListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFarmListRequest.ProtoReflect.Descriptor instead.
func (*GetFarmListRequest) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{10}
}

func (x *GetFarmListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFarmListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetFarmListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Farms         []*Farm                `protobuf:"bytes,1,rep,name=farms,proto3" json:"farms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFarmListResponse) Reset() {
	*x = GetFarmListResponse{}
	mi := &file_farm_v1_farm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFarmListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFarmListResponse) ProtoMessage() {}

func (x *GetFarmListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFarmListResponse.ProtoReflect.Descriptor instead.
func (*GetFarmListResponse) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{11}
}

func (x *GetFarmListResponse) GetFarms() []*Farm {
	if x != nil {
		return x.Farms
	}
	return nil
}

type UpdateFarmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Farm          *UpdateFarmData        `protobuf:"bytes,1,opt,name=farm,proto3,oneof" json:"farm,omitempty"`
	Address       *UpdateFarmAddressData `protobuf:"bytes,2,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFarmsRequest) Reset() {
	*x = UpdateFarmsRequest{}
	mi := &file_farm_v1_farm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFarmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFarmsRequest) ProtoMessage() {}

func (x *UpdateFarmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFarmsRequest.ProtoReflect.Descriptor instead.
func (*UpdateFarmsRequest) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateFarmsRequest) GetFarm() *UpdateFarmData {
	if x != nil {
		return x.Farm
	}
	return nil
}

func (x *UpdateFarmsRequest) GetAddress() *UpdateFarmAddressData {
	if x != nil {
		return x.Address
	}
	return nil
}

type UpdateFarmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmId        *string                `protobuf:"bytes,1,opt,name=farm_id,json=farmId,proto3,oneof" json:"farm_id,omitempty"`
	FarmName      *string                `protobuf:"bytes,2,opt,name=farm_name,json=farmName,proto3,oneof" json:"farm_name,omitempty"`
	AddressId     *string                `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3,oneof" json:"address_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFarmsResponse) Reset() {
	*x = UpdateFarmsResponse{}
	mi := &file_farm_v1_farm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFarmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFarmsResponse) ProtoMessage() {}

func (x *UpdateFarmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFarmsResponse.ProtoReflect.Descriptor instead.
func (*UpdateFarmsResponse) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateFarmsResponse) GetFarmId() string {
	if x != nil && x.FarmId != nil {
		return *x.FarmId
	}
	return ""
}

func (x *UpdateFarmsResponse) GetFarmName() string {
	if x != nil && x.FarmName != nil {
		return *x.FarmName
	}
	return ""
}

func (x *UpdateFarmsResponse) GetAddressId() string {
	if x != nil && x.AddressId != nil {
		return *x.AddressId
	}
	return ""
}

func (x *UpdateFarmsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateFarmsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteFarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFarmRequest) Reset() {
	*x = DeleteFarmRequest{}
	mi := &file_farm_v1_farm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFarmRequest) ProtoMessage() {}

func (x *DeleteFarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFarmRequest.ProtoReflect.Descriptor instead.
func (*DeleteFarmRequest) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFarmRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteFarmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFarmResponse) Reset() {
	*x = DeleteFarmResponse{}
	mi := &file_farm_v1_farm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFarmResponse) ProtoMessage() {}

func (x *DeleteFarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farm_v1_farm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFarmResponse.ProtoReflect.Descriptor instead.
func (*DeleteFarmResponse) Descriptor() ([]byte, []int) {
	return file_farm_v1_farm_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteFarmResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteFarmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteFarmResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_farm_v1_farm_proto protoreflect.FileDescriptor

const file_farm_v1_farm_proto_rawDesc = "" +
	"\n" +
	"\x12farm/v1/farm.proto\x12\afarm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x02\n" +
	"\vFarmAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x18\n" +
	"\avillage\x18\x03 \x01(\tR\avillage\x12!\n" +
	"\fsub_district\x18\x04 \x01(\tR\vsubDistrict\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x1f\n" +
	"\vpostal_code\x18\a \x01(\tR\n" +
	"postalCode\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf3\x02\n" +
	"\x04Farm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfarmer_id\x18\x02 \x01(\tR\bfarmerId\x12\x1b\n" +
	"\tfarm_name\x18\x03 \x01(\tR\bfarmName\x12\x1b\n" +
	"\tfarm_type\x18\x04 \x01(\tR\bfarmType\x12\x1b\n" +
	"\tfarm_size\x18\x05 \x01(\x01R\bfarmSize\x12\x1f\n" +
	"\vfarm_status\x18\x06 \x01(\tR\n" +
	"farmStatus\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12.\n" +
	"\aaddress\x18\b \x01(\v2\x14.farm.v1.FarmAddressR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb9\x01\n" +
	"\x11CreateFarmAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x18\n" +
	"\avillage\x18\x02 \x01(\tR\avillage\x12!\n" +
	"\fsub_district\x18\x03 \x01(\tR\vsubDistrict\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\"\xc3\x01\n" +
	"\n" +
	"CreateFarm\x12\x1b\n" +
	"\tfarmer_id\x18\x01 \x01(\tR\bfarmerId\x12\x1b\n" +
	"\tfarm_name\x18\x02 \x01(\tR\bfarmName\x12\x1b\n" +
	"\tfarm_type\x18\x03 \x01(\tR\bfarmType\x12\x1b\n" +
	"\tfarm_size\x18\x04 \x01(\x01R\bfarmSize\x12\x1f\n" +
	"\vfarm_status\x18\x05 \x01(\tR\n" +
	"farmStatus\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xba\x01\n" +
	"\x0eUpdateFarmData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfarm_name\x18\x03 \x01(\tR\bfarmName\x12\x1b\n" +
	"\tfarm_type\x18\x04 \x01(\tR\bfarmType\x12\x1b\n" +
	"\tfarm_size\x18\x05 \x01(\x01R\bfarmSize\x12\x1f\n" +
	"\vfarm_status\x18\x06 \x01(\tR\n" +
	"farmStatus\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\xcd\x01\n" +
	"\x15UpdateFarmAddressData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x18\n" +
	"\avillage\x18\x03 \x01(\tR\avillage\x12!\n" +
	"\fsub_district\x18\x04 \x01(\tR\vsubDistrict\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x1f\n" +
	"\vpostal_code\x18\a \x01(\tR\n" +
	"postalCode\"r\n" +
	"\x11CreateFarmRequest\x12'\n" +
	"\x04farm\x18\x01 \x01(\v2\x13.farm.v1.CreateFarmR\x04farm\x124\n" +
	"\aaddress\x18\x02 \x01(\v2\x1a.farm.v1.CreateFarmAddressR\aaddress\"\x93\x01\n" +
	"\x12CreateFarmResponse\x12\x17\n" +
	"\afarm_id\x18\x01 \x01(\tR\x06farmId\x12\x1b\n" +
	"\tfarm_name\x18\x02 \x01(\tR\bfarmName\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msg\"$\n" +
	"\x12GetFarmByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x13GetFarmByIDResponse\x12!\n" +
	"\x04farm\x18\x01 \x01(\v2\r.farm.v1.FarmR\x04farm\"B\n" +
	"\x12GetFarmListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\":\n" +
	"\x13GetFarmListResponse\x12#\n" +
	"\x05farms\x18\x01 \x03(\v2\r.farm.v1.FarmR\x05farms\"\x9a\x01\n" +
	"\x12UpdateFarmsRequest\x120\n" +
	"\x04farm\x18\x01 \x01(\v2\x17.farm.v1.UpdateFarmDataH\x00R\x04farm\x88\x01\x01\x12=\n" +
	"\aaddress\x18\x02 \x01(\v2\x1e.farm.v1.UpdateFarmAddressDataH\x01R\aaddress\x88\x01\x01B\a\n" +
	"\x05_farmB\n" +
	"\n" +
	"\b_address\"\xcc\x01\n" +
	"\x13UpdateFarmsResponse\x12\x1c\n" +
	"\afarm_id\x18\x01 \x01(\tH\x00R\x06farmId\x88\x01\x01\x12 \n" +
	"\tfarm_name\x18\x02 \x01(\tH\x01R\bfarmName\x88\x01\x01\x12\"\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tH\x02R\taddressId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msgB\n" +
	"\n" +
	"\b_farm_idB\f\n" +
	"\n" +
	"_farm_nameB\r\n" +
	"\v_address_id\")\n" +
	"\x11DeleteFarmRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"N\n" +
	"\x12DeleteFarmResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg2\x83\x03\n" +
	"\vFarmService\x12I\n" +
	"\n" +
	"CreateFarm\x12\x1a.farm.v1.CreateFarmRequest\x1a\x1b.farm.v1.CreateFarmResponse(\x010\x01\x12H\n" +
	"\vGetFarmByID\x12\x1b.farm.v1.GetFarmByIDRequest\x1a\x1c.farm.v1.GetFarmByIDResponse\x12J\n" +
	"\vGetFarmList\x12\x1b.farm.v1.GetFarmListRequest\x1a\x1c.farm.v1.GetFarmListResponse0\x01\x12L\n" +
	"\vUpdateFarms\x12\x1b.farm.v1.UpdateFarmsRequest\x1a\x1c.farm.v1.UpdateFarmsResponse(\x010\x01\x12E\n" +
	"\n" +
	"DeleteFarm\x12\x1a.farm.v1.DeleteFarmRequest\x1a\x1b.farm.v1.DeleteFarmResponseb\x06proto3"

var (
	file_farm_v1_farm_proto_rawDescOnce sync.Once
	file_farm_v1_farm_proto_rawDescData []byte
)

func file_farm_v1_farm_proto_rawDescGZIP() []byte {
	file_farm_v1_farm_proto_rawDescOnce.Do(func() {
		file_farm_v1_farm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_farm_v1_farm_proto_rawDesc), len(file_farm_v1_farm_proto_rawDesc)))
	})
	return file_farm_v1_farm_proto_rawDescData
}

var file_farm_v1_farm_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_farm_v1_farm_proto_goTypes = []any{
	(*FarmAddress)(nil),           // 0: farm.v1.FarmAddress
	(*Farm)(nil),                  // 1: farm.v1.Farm
	(*CreateFarmAddress)(nil),     // 2: farm.v1.CreateFarmAddress
	(*CreateFarm)(nil),            // 3: farm.v1.CreateFarm
	(*UpdateFarmData)(nil),        // 4: farm.v1.UpdateFarmData
	(*UpdateFarmAddressData)(nil), // 5: farm.v1.UpdateFarmAddressData
	(*CreateFarmRequest)(nil),     // 6: farm.v1.CreateFarmRequest
	(*CreateFarmResponse)(nil),    // 7: farm.v1.CreateFarmResponse
	(*GetFarmByIDRequest)(nil),    // 8: farm.v1.GetFarmByIDRequest
	(*GetFarmByIDResponse)(nil),   // 9: farm.v1.GetFarmByIDResponse
	(*GetFarmListRequest)(nil),    // 10: farm.v1.GetFarmListRequest
	(*GetFarmListResponse)(nil),   // 11: farm.v1.GetFarmListResponse
	(*UpdateFarmsRequest)(nil),    // 12: farm.v1.UpdateFarmsRequest
	(*UpdateFarmsResponse)(nil),   // 13: farm.v1.UpdateFarmsResponse
	(*DeleteFarmRequest)(nil),     // 14: farm.v1.DeleteFarmRequest
	(*DeleteFarmResponse)(nil),    // 15: farm.v1.DeleteFarmResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_farm_v1_farm_proto_depIdxs = []int32{
	16, // 0: farm.v1.FarmAddress.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: farm.v1.FarmAddress.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: farm.v1.Farm.address:type_name -> farm.v1.FarmAddress
	16, // 3: farm.v1.Farm.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: farm.v1.Farm.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: farm.v1.CreateFarmRequest.farm:type_name -> farm.v1.CreateFarm
	2,  // 6: farm.v1.CreateFarmRequest.address:type_name -> farm.v1.CreateFarmAddress
	1,  // 7: farm.v1.GetFarmByIDResponse.farm:type_name -> farm.v1.Farm
	1,  // 8: farm.v1.GetFarmListResponse.farms:type_name -> farm.v1.Farm
	4,  // 9: farm.v1.UpdateFarmsRequest.farm:type_name -> farm.v1.UpdateFarmData
	5,  // 10: farm.v1.UpdateFarmsRequest.address:type_name -> farm.v1.UpdateFarmAddressData
	6,  // 11: farm.v1.FarmService.CreateFarm:input_type -> farm.v1.CreateFarmRequest
	8,  // 12: farm.v1.FarmService.GetFarmByID:input_type -> farm.v1.GetFarmByIDRequest
	10, // 13: farm.v1.FarmService.GetFarmList:input_type -> farm.v1.GetFarmListRequest
	12, // 14: farm.v1.FarmService.UpdateFarms:input_type -> farm.v1.UpdateFarmsRequest
	14, // 15: farm.v1.FarmService.DeleteFarm:input_type -> farm.v1.DeleteFarmRequest
	7,  // 16: farm.v1.FarmService.CreateFarm:output_type -> farm.v1.CreateFarmResponse
	9,  // 17: farm.v1.FarmService.GetFarmByID:output_type -> farm.v1.GetFarmByIDResponse
	11, // 18: farm.v1.FarmService.GetFarmList:output_type -> farm.v1.GetFarmListResponse
	13, // 19: farm.v1.FarmService.UpdateFarms:output_type -> farm.v1.UpdateFarmsResponse
	15, // 20: farm.v1.FarmService.DeleteFarm:output_type -> farm.v1.DeleteFarmResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_farm_v1_farm_proto_init() }
func file_farm_v1_farm_proto_init() {
	if File_farm_v1_farm_proto != nil {
		return
	}
	file_farm_v1_farm_proto_msgTypes[12].OneofWrappers = []any{}
	file_farm_v1_farm_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_farm_v1_farm_proto_rawDesc), len(file_farm_v1_farm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_farm_v1_farm_proto_goTypes,
		DependencyIndexes: file_farm_v1_farm_proto_depIdxs,
		MessageInfos:      file_farm_v1_farm_proto_msgTypes,
	}.Build()
	File_farm_v1_farm_proto = out.File
	file_farm_v1_farm_proto_goTypes = nil
	file_farm_v1_farm_proto_depIdxs = nil
}
