package pkg

type ConfigKeyKafka string

const (
	BOOTSTRAP_SERVERS                     ConfigKeyKafka = "bootstrap.servers"
	GROUP_ID                              ConfigKeyKafka = "group.id"
	FETCH_MIN_BYTES                       ConfigKeyKafka = "fetch.min.bytes"
	FETCH_MAX_WAIT_MS                     ConfigKeyKafka = "fetch.max.wait.ms"
	FETCH_MAX_BYTES                       ConfigKeyKafka = "fetch.max.bytes"
	MAX_POLL_RECORDS                      ConfigKeyKafka = "max.poll.records"
	MAX_PARTITION_FETCH_BYTES             ConfigKeyKafka = "max.partition.fetch.bytes"
	SESSION_TIMEOUT_MS                    ConfigKeyKafka = "session.timeout.ms"
	HEARTBEAT_INTERVAL_MS                 ConfigKeyKafka = "heartbeat.interval.ms"
	MAX_POLL_INTERVAL_MS                  ConfigKeyKafka = "max.poll.interval.ms"
	DEFAULT_API_TIMEOUT_MS                ConfigKeyKafka = "default.api.timeout.ms"
	AUTO_OFFSET_RESET                     ConfigKeyKafka = "auto.offset.reset"
	ENABLE_AUTO_COMMIT                    ConfigKeyKafka = "enable.auto.commit"
	PARTITION_ASSIGNMENT_STRATEGY         ConfigKeyKafka = "partition.assignment.strategy"
	CLIENT_ID                             ConfigKeyKafka = "client.id"
	GROUP_INSTANCE_ID                     ConfigKeyKafka = "group.instance.id"
	CLIENT_RACK                           ConfigKeyKafka = "client.rack"
	RECEIVE_BUFFER_BYTES                  ConfigKeyKafka = "receive.buffer.bytes"
	OFFSETS_RETENTION_MINUTES             ConfigKeyKafka = "offsets.retention.minutes"
	AUTO_COMMIT_INTERVAL_MS               ConfigKeyKafka = "auto.commit.interval.ms"
	ACKS                                  ConfigKeyKafka = "acks"
	MAX_BLOCK_MS                          ConfigKeyKafka = "max.block.ms"
	DELIVERY_TIMEOUT_MS                   ConfigKeyKafka = "delivery.timeout.ms"
	REQUEST_TIMEOUT_MS                    ConfigKeyKafka = "request.timeout.ms"
	RETRIES                               ConfigKeyKafka = "retries"
	RETRY_BACKOFF_MS                      ConfigKeyKafka = "retry.backoff.ms"
	LINGER_MS                             ConfigKeyKafka = "linger.ms"
	BUFFER_MEMORY                         ConfigKeyKafka = "buffer.memory"
	COMPRESION_TYPE                       ConfigKeyKafka = "compression.type"
	BATCH_SIZE                            ConfigKeyKafka = "batch.size"
	MAX_REQUEST_SIZE                      ConfigKeyKafka = "max.request.size"
	MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION ConfigKeyKafka = "max.in.flight.requests.per.connection"
	SEND_BUFFER_BYTES                     ConfigKeyKafka = "send.buffer.bytes"
	ENABLE_IDEMPOTENCE                    ConfigKeyKafka = "enable.idempotence"
	TRANSACTIONAL_ID                      ConfigKeyKafka = "transactional.id"
)
