// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ranch/v1/ranch.proto

package pbgen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RanchService_RegisterAnimal_FullMethodName = "/ranch.v1.RanchService/RegisterAnimal"
)

// RanchServiceClient is the client API for RanchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RanchServiceClient interface {
	RegisterAnimal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterAnimalRequest, RegisterAnimalResponse], error)
}

type ranchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRanchServiceClient(cc grpc.ClientConnInterface) RanchServiceClient {
	return &ranchServiceClient{cc}
}

func (c *ranchServiceClient) RegisterAnimal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterAnimalRequest, RegisterAnimalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RanchService_ServiceDesc.Streams[0], RanchService_RegisterAnimal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterAnimalRequest, RegisterAnimalResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RanchService_RegisterAnimalClient = grpc.BidiStreamingClient[RegisterAnimalRequest, RegisterAnimalResponse]

// RanchServiceServer is the server API for RanchService service.
// All implementations must embed UnimplementedRanchServiceServer
// for forward compatibility.
type RanchServiceServer interface {
	RegisterAnimal(grpc.BidiStreamingServer[RegisterAnimalRequest, RegisterAnimalResponse]) error
	mustEmbedUnimplementedRanchServiceServer()
}

// UnimplementedRanchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRanchServiceServer struct{}

func (UnimplementedRanchServiceServer) RegisterAnimal(grpc.BidiStreamingServer[RegisterAnimalRequest, RegisterAnimalResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RegisterAnimal not implemented")
}
func (UnimplementedRanchServiceServer) mustEmbedUnimplementedRanchServiceServer() {}
func (UnimplementedRanchServiceServer) testEmbeddedByValue()                      {}

// UnsafeRanchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RanchServiceServer will
// result in compilation errors.
type UnsafeRanchServiceServer interface {
	mustEmbedUnimplementedRanchServiceServer()
}

func RegisterRanchServiceServer(s grpc.ServiceRegistrar, srv RanchServiceServer) {
	// If the following call pancis, it indicates UnimplementedRanchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RanchService_ServiceDesc, srv)
}

func _RanchService_RegisterAnimal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RanchServiceServer).RegisterAnimal(&grpc.GenericServerStream[RegisterAnimalRequest, RegisterAnimalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RanchService_RegisterAnimalServer = grpc.BidiStreamingServer[RegisterAnimalRequest, RegisterAnimalResponse]

// RanchService_ServiceDesc is the grpc.ServiceDesc for RanchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RanchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ranch.v1.RanchService",
	HandlerType: (*RanchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterAnimal",
			Handler:       _RanchService_RegisterAnimal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ranch/v1/ranch.proto",
}
