// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ranch/v1/ranch.proto

package pbgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAnimalRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FarmId           string                 `protobuf:"bytes,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Species          string                 `protobuf:"bytes,4,opt,name=species,proto3" json:"species,omitempty"`
	Breed            string                 `protobuf:"bytes,5,opt,name=breed,proto3" json:"breed,omitempty"`
	BirthDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	OriginType       OriginType             `protobuf:"varint,7,opt,name=origin_type,json=originType,proto3,enum=ranch.animal.v1.OriginType" json:"origin_type,omitempty"`
	OriginFrom       *string                `protobuf:"bytes,8,opt,name=origin_from,json=originFrom,proto3,oneof" json:"origin_from,omitempty"`
	PurchasedPrice   *float64               `protobuf:"fixed64,9,opt,name=purchased_price,json=purchasedPrice,proto3,oneof" json:"purchased_price,omitempty"`
	Gender           GENDER                 `protobuf:"varint,10,opt,name=gender,proto3,enum=ranch.animal.v1.GENDER" json:"gender,omitempty"`
	Weight           float64                `protobuf:"fixed64,11,opt,name=weight,proto3" json:"weight,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=registration_date,json=registrationDate,proto3,oneof" json:"registration_date,omitempty"`
	Notes            string                 `protobuf:"bytes,13,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterAnimalRequest) Reset() {
	*x = RegisterAnimalRequest{}
	mi := &file_ranch_v1_ranch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAnimalRequest) ProtoMessage() {}

func (x *RegisterAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ranch_v1_ranch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAnimalRequest.ProtoReflect.Descriptor instead.
func (*RegisterAnimalRequest) Descriptor() ([]byte, []int) {
	return file_ranch_v1_ranch_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAnimalRequest) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *RegisterAnimalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAnimalRequest) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *RegisterAnimalRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *RegisterAnimalRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *RegisterAnimalRequest) GetOriginType() OriginType {
	if x != nil {
		return x.OriginType
	}
	return OriginType_ORIGIN_TYPE_UNSPECIFIED
}

func (x *RegisterAnimalRequest) GetOriginFrom() string {
	if x != nil && x.OriginFrom != nil {
		return *x.OriginFrom
	}
	return ""
}

func (x *RegisterAnimalRequest) GetPurchasedPrice() float64 {
	if x != nil && x.PurchasedPrice != nil {
		return *x.PurchasedPrice
	}
	return 0
}

func (x *RegisterAnimalRequest) GetGender() GENDER {
	if x != nil {
		return x.Gender
	}
	return GENDER_GENDER_UNSPECIFIED
}

func (x *RegisterAnimalRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RegisterAnimalRequest) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

func (x *RegisterAnimalRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RegisterAnimalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animal        *Animal                `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAnimalResponse) Reset() {
	*x = RegisterAnimalResponse{}
	mi := &file_ranch_v1_ranch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAnimalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAnimalResponse) ProtoMessage() {}

func (x *RegisterAnimalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranch_v1_ranch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAnimalResponse.ProtoReflect.Descriptor instead.
func (*RegisterAnimalResponse) Descriptor() ([]byte, []int) {
	return file_ranch_v1_ranch_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAnimalResponse) GetAnimal() *Animal {
	if x != nil {
		return x.Animal
	}
	return nil
}

var File_ranch_v1_ranch_proto protoreflect.FileDescriptor

const file_ranch_v1_ranch_proto_rawDesc = "" +
	"\n" +
	"\x14ranch/v1/ranch.proto\x12\branch.v1\x1a\x1cranch/animal/v1/animal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x04\n" +
	"\x15RegisterAnimalRequest\x12\x17\n" +
	"\afarm_id\x18\x01 \x01(\tR\x06farmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x04 \x01(\tR\aspecies\x12\x14\n" +
	"\x05breed\x18\x05 \x01(\tR\x05breed\x129\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12<\n" +
	"\vorigin_type\x18\a \x01(\x0e2\x1b.ranch.animal.v1.OriginTypeR\n" +
	"originType\x12$\n" +
	"\vorigin_from\x18\b \x01(\tH\x00R\n" +
	"originFrom\x88\x01\x01\x12,\n" +
	"\x0fpurchased_price\x18\t \x01(\x01H\x01R\x0epurchasedPrice\x88\x01\x01\x12/\n" +
	"\x06gender\x18\n" +
	" \x01(\x0e2\x17.ranch.animal.v1.GENDERR\x06gender\x12\x16\n" +
	"\x06weight\x18\v \x01(\x01R\x06weight\x12L\n" +
	"\x11registration_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x10registrationDate\x88\x01\x01\x12\x14\n" +
	"\x05notes\x18\r \x01(\tR\x05notesB\x0e\n" +
	"\f_origin_fromB\x12\n" +
	"\x10_purchased_priceB\x14\n" +
	"\x12_registration_date\"I\n" +
	"\x16RegisterAnimalResponse\x12/\n" +
	"\x06animal\x18\x01 \x01(\v2\x17.ranch.animal.v1.AnimalR\x06animal2g\n" +
	"\fRanchService\x12W\n" +
	"\x0eRegisterAnimal\x12\x1f.ranch.v1.RegisterAnimalRequest\x1a .ranch.v1.RegisterAnimalResponse(\x010\x01b\x06proto3"

var (
	file_ranch_v1_ranch_proto_rawDescOnce sync.Once
	file_ranch_v1_ranch_proto_rawDescData []byte
)

func file_ranch_v1_ranch_proto_rawDescGZIP() []byte {
	file_ranch_v1_ranch_proto_rawDescOnce.Do(func() {
		file_ranch_v1_ranch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ranch_v1_ranch_proto_rawDesc), len(file_ranch_v1_ranch_proto_rawDesc)))
	})
	return file_ranch_v1_ranch_proto_rawDescData
}

var file_ranch_v1_ranch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ranch_v1_ranch_proto_goTypes = []any{
	(*RegisterAnimalRequest)(nil),  // 0: ranch.v1.RegisterAnimalRequest
	(*RegisterAnimalResponse)(nil), // 1: ranch.v1.RegisterAnimalResponse
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
	(OriginType)(0),                // 3: ranch.animal.v1.OriginType
	(GENDER)(0),                    // 4: ranch.animal.v1.GENDER
	(*Animal)(nil),                 // 5: ranch.animal.v1.Animal
}
var file_ranch_v1_ranch_proto_depIdxs = []int32{
	2, // 0: ranch.v1.RegisterAnimalRequest.birth_date:type_name -> google.protobuf.Timestamp
	3, // 1: ranch.v1.RegisterAnimalRequest.origin_type:type_name -> ranch.animal.v1.OriginType
	4, // 2: ranch.v1.RegisterAnimalRequest.gender:type_name -> ranch.animal.v1.GENDER
	2, // 3: ranch.v1.RegisterAnimalRequest.registration_date:type_name -> google.protobuf.Timestamp
	5, // 4: ranch.v1.RegisterAnimalResponse.animal:type_name -> ranch.animal.v1.Animal
	0, // 5: ranch.v1.RanchService.RegisterAnimal:input_type -> ranch.v1.RegisterAnimalRequest
	1, // 6: ranch.v1.RanchService.RegisterAnimal:output_type -> ranch.v1.RegisterAnimalResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ranch_v1_ranch_proto_init() }
func file_ranch_v1_ranch_proto_init() {
	if File_ranch_v1_ranch_proto != nil {
		return
	}
	file_ranch_animal_v1_animal_proto_init()
	file_ranch_v1_ranch_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ranch_v1_ranch_proto_rawDesc), len(file_ranch_v1_ranch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ranch_v1_ranch_proto_goTypes,
		DependencyIndexes: file_ranch_v1_ranch_proto_depIdxs,
		MessageInfos:      file_ranch_v1_ranch_proto_msgTypes,
	}.Build()
	File_ranch_v1_ranch_proto = out.File
	file_ranch_v1_ranch_proto_goTypes = nil
	file_ranch_v1_ranch_proto_depIdxs = nil
}
