syntax = "proto3";

package ranch.v1;

import "ranch/animal/v1/animal.proto";
import "google/protobuf/timestamp.proto";


message RegisterAnimalRequest {
  string farm_id  = 1;
  string name = 2;
  string species = 4;
  string breed = 5;
  optional google.protobuf.Timestamp birth_date = 6;
  ranch.animal.v1.OriginType origin_type = 7;
  optional string origin_from = 8;
  optional double purchased_price = 9;
  ranch.animal.v1.GENDER gender = 10; 
  double weight = 11;
  google.protobuf.Timestamp registration_date = 12;
  string notes = 13;
}

message RegisterAnimalResponse {
  string msg = 1;
  string status = 2;
  optional ranch.animal.v1.Animal animal = 3;
}

service RanchService {
  rpc RegisterAnimal(stream RegisterAnimalRequest) returns (stream RegisterAnimalResponse);
}
