// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: farmer/v1/farmer.proto

package pbgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Farmer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Verified      bool                   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Farmer) Reset() {
	*x = Farmer{}
	mi := &file_farmer_v1_farmer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Farmer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Farmer) ProtoMessage() {}

func (x *Farmer) ProtoReflect() protoreflect.Message {
	mi := &file_farmer_v1_farmer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Farmer.ProtoReflect.Descriptor instead.
func (*Farmer) Descriptor() ([]byte, []int) {
	return file_farmer_v1_farmer_proto_rawDescGZIP(), []int{0}
}

func (x *Farmer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Farmer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Farmer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Farmer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Farmer) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Farmer) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Farmer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FarmerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmerProfileRequest) Reset() {
	*x = FarmerProfileRequest{}
	mi := &file_farmer_v1_farmer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmerProfileRequest) ProtoMessage() {}

func (x *FarmerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farmer_v1_farmer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmerProfileRequest.ProtoReflect.Descriptor instead.
func (*FarmerProfileRequest) Descriptor() ([]byte, []int) {
	return file_farmer_v1_farmer_proto_rawDescGZIP(), []int{1}
}

func (x *FarmerProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FarmerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Farmer        *Farmer                `protobuf:"bytes,1,opt,name=farmer,proto3" json:"farmer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmerProfileResponse) Reset() {
	*x = FarmerProfileResponse{}
	mi := &file_farmer_v1_farmer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmerProfileResponse) ProtoMessage() {}

func (x *FarmerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farmer_v1_farmer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmerProfileResponse.ProtoReflect.Descriptor instead.
func (*FarmerProfileResponse) Descriptor() ([]byte, []int) {
	return file_farmer_v1_farmer_proto_rawDescGZIP(), []int{2}
}

func (x *FarmerProfileResponse) GetFarmer() *Farmer {
	if x != nil {
		return x.Farmer
	}
	return nil
}

type UpdateFarmerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      *string                `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3,oneof" json:"full_name,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFarmerProfileRequest) Reset() {
	*x = UpdateFarmerProfileRequest{}
	mi := &file_farmer_v1_farmer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFarmerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFarmerProfileRequest) ProtoMessage() {}

func (x *UpdateFarmerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farmer_v1_farmer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFarmerProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateFarmerProfileRequest) Descriptor() ([]byte, []int) {
	return file_farmer_v1_farmer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFarmerProfileRequest) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *UpdateFarmerProfileRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateFarmerProfileRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type UpdateFarmerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Farmer                `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFarmerProfileResponse) Reset() {
	*x = UpdateFarmerProfileResponse{}
	mi := &file_farmer_v1_farmer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFarmerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFarmerProfileResponse) ProtoMessage() {}

func (x *UpdateFarmerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farmer_v1_farmer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFarmerProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateFarmerProfileResponse) Descriptor() ([]byte, []int) {
	return file_farmer_v1_farmer_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFarmerProfileResponse) GetValue() *Farmer {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_farmer_v1_farmer_proto protoreflect.FileDescriptor

const file_farmer_v1_farmer_proto_rawDesc = "" +
	"\n" +
	"\x16farmer/v1/farmer.proto\x12\tfarmer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\x06Farmer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"&\n" +
	"\x14FarmerProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x15FarmerProfileResponse\x12)\n" +
	"\x06farmer\x18\x01 \x01(\v2\x11.farmer.v1.FarmerR\x06farmer\"\x96\x01\n" +
	"\x1aUpdateFarmerProfileRequest\x12 \n" +
	"\tfull_name\x18\x01 \x01(\tH\x00R\bfullName\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x02R\x05phone\x88\x01\x01B\f\n" +
	"\n" +
	"_full_nameB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"F\n" +
	"\x1bUpdateFarmerProfileResponse\x12'\n" +
	"\x05value\x18\x01 \x01(\v2\x11.farmer.v1.FarmerR\x05value2\xbd\x01\n" +
	"\rFarmerService\x12R\n" +
	"\rFarmerProfile\x12\x1f.farmer.v1.FarmerProfileRequest\x1a .farmer.v1.FarmerProfileResponse\x12X\n" +
	"\x13UpdateFarmerProfile\x12\x1f.farmer.v1.FarmerProfileRequest\x1a .farmer.v1.FarmerProfileResponseb\x06proto3"

var (
	file_farmer_v1_farmer_proto_rawDescOnce sync.Once
	file_farmer_v1_farmer_proto_rawDescData []byte
)

func file_farmer_v1_farmer_proto_rawDescGZIP() []byte {
	file_farmer_v1_farmer_proto_rawDescOnce.Do(func() {
		file_farmer_v1_farmer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_farmer_v1_farmer_proto_rawDesc), len(file_farmer_v1_farmer_proto_rawDesc)))
	})
	return file_farmer_v1_farmer_proto_rawDescData
}

var file_farmer_v1_farmer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_farmer_v1_farmer_proto_goTypes = []any{
	(*Farmer)(nil),                      // 0: farmer.v1.Farmer
	(*FarmerProfileRequest)(nil),        // 1: farmer.v1.FarmerProfileRequest
	(*FarmerProfileResponse)(nil),       // 2: farmer.v1.FarmerProfileResponse
	(*UpdateFarmerProfileRequest)(nil),  // 3: farmer.v1.UpdateFarmerProfileRequest
	(*UpdateFarmerProfileResponse)(nil), // 4: farmer.v1.UpdateFarmerProfileResponse
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_farmer_v1_farmer_proto_depIdxs = []int32{
	5, // 0: farmer.v1.Farmer.registered_at:type_name -> google.protobuf.Timestamp
	5, // 1: farmer.v1.Farmer.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: farmer.v1.FarmerProfileResponse.farmer:type_name -> farmer.v1.Farmer
	0, // 3: farmer.v1.UpdateFarmerProfileResponse.value:type_name -> farmer.v1.Farmer
	1, // 4: farmer.v1.FarmerService.FarmerProfile:input_type -> farmer.v1.FarmerProfileRequest
	1, // 5: farmer.v1.FarmerService.UpdateFarmerProfile:input_type -> farmer.v1.FarmerProfileRequest
	2, // 6: farmer.v1.FarmerService.FarmerProfile:output_type -> farmer.v1.FarmerProfileResponse
	2, // 7: farmer.v1.FarmerService.UpdateFarmerProfile:output_type -> farmer.v1.FarmerProfileResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_farmer_v1_farmer_proto_init() }
func file_farmer_v1_farmer_proto_init() {
	if File_farmer_v1_farmer_proto != nil {
		return
	}
	file_farmer_v1_farmer_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_farmer_v1_farmer_proto_rawDesc), len(file_farmer_v1_farmer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_farmer_v1_farmer_proto_goTypes,
		DependencyIndexes: file_farmer_v1_farmer_proto_depIdxs,
		MessageInfos:      file_farmer_v1_farmer_proto_msgTypes,
	}.Build()
	File_farmer_v1_farmer_proto = out.File
	file_farmer_v1_farmer_proto_goTypes = nil
	file_farmer_v1_farmer_proto_depIdxs = nil
}
